services:
  mongodb:
    image: mongo:5.0.15
    environment:
      MONGO_INITDB_ROOT_USERNAME: taitnt
      MONGO_INITDB_ROOT_PASSWORD: Tai17042002
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

    # docker compose -p hoidanit-mongodb-4rn up -d
